### PR TITLE
Architectury 1.21.1/dev general porting

### PR DESCRIPTION
**Pull request by Aperre**
fixed all CompoundTags compilation errors and others from the equipment/ directory

### CODE REVIEW

**Comment by tamimbook** [comment]
@Aperre do you  making the mod compatible with MC1.21.1?

**Comment by Aperre** [comment]
Yeah im working on the 1.21.1 branch I just have a small problem with packets right now

**Comment by tamimbook** [comment]
@Aperre I see thanks for your hard work! also I'm hoping if you can also add neoforge platform in the update?

**Comment by SolidStateDj** [comment]
@tamimbook That's a necessary part required for 1.21.1 support.

And @Aperre , I've slowly been chugging away at the packet issues. Might make a draft PR you can use as a guide to follow, but unsure if my methods are even correct.

**Comment by Aperre** [comment]
@SolidStateDj Okay that works. Let's just try to get it to compile then focus fixing the bugs.

**Comment by Aperre** [comment]
We are down to only 35 errors
Edit: now 21 errors. which are from: JEI integration, ConfigCommand and ElectroZapperS2CPacket

**Comment by Aperre** [comment]
common builds with no errors. I'm gonna start working on neoforge

**Comment by RedHolms** [comment]
> common builds with no errors. I'm gonna start working on neoforge

I just wanna say that I fucking love you and thank you for your enormous work

**Comment by patryk3211** [comment]
Thank you for handling this. Make sure to let me know when you're ready for review and merge.

**Comment by Aperre** [comment]
No problem man, I am currently trying to get a working neoforge port I will commit it in a bit after I check the code and fix the rendering bugs with the wires

**Comment by Aperre** [comment]
Good news, it launches on neoforge. I still have a couple of problems to figure out I will get back to it as soon as I can.

**Comment by tamimbook** [comment]
@Aperre do you facing any problem? with neoforge? how much work is done?

**Comment by Aperre** [comment]
@tamimbook I think I am almost done. I am currently just checking each object to see if there are any errors or things misbehaving.

**Comment by Aperre** [comment]
@patryk3211 I think I am done and ready to merge
BTW I have not worked on fabric. Might work on it in another pull request but unsure (too much work)

**Comment by RedHolms** [comment]
> @patryk3211 I think I am done and ready to merge
> BTW I have not worked on fabric. Might work on it in another pull request but unsure (too much work)

you're my favourite person. Thank you

**Comment by patryk3211** [comment]
> @patryk3211 I think I am done and ready to merge
> BTW I have not worked on fabric. Might work on it in another pull request but unsure (too much work)

I'd say don't bother, create fabric doesnt support 1.21.1 anyways.

**Comment by Aperre** [comment]
> I'd say don't bother, create fabric doesnt support 1.21.1 anyways.

I think the Electromagnet is broken. I have not been able to fix it. Thats about the only thing left.
(I am not sure how to use it could be just me)

File: src/main/java/org/patryk3211/powergrid/electricity/base/ElectricBlock.java [hunk 1]
```diff
@@ -95,4 +98,11 @@ public float resistance() {
     public float resistance(String suffix) {
         return ResistanceValues.get(this, suffix);
     }
+
+    public abstract InteractionResult use(BlockState state, Level world, BlockPos pos, Player player, InteractionHand hand, BlockHitResult hit);
```
Comment (patryk3211) [inline src/main/java/org/patryk3211/powergrid/electricity/base/ElectricBlock.java]: This method is defined as abstract, why does it not have a default implementation of returning `PASS` if that is what its common definition?

File: src/main/java/org/patryk3211/powergrid/kinetics/base/ElectricKineticBlock.java [hunk 2]
```diff
@@ -81,4 +85,11 @@ public float resistance() {
     public float resistance(String suffix) {
         return ResistanceValues.get(this, suffix);
     }
+
+    public abstract InteractionResult use(BlockState state, Level level, BlockPos pos, Player player, InteractionHand hand, BlockHitResult hit);
```
Comment (patryk3211) [inline src/main/java/org/patryk3211/powergrid/kinetics/base/ElectricKineticBlock.java]: Once again, why not have a default implementation here?

File: src/main/java/org/patryk3211/powergrid/network/PacketSet.java [hunk 3]
```diff
@@ -0,0 +1,217 @@
...
+        @Override
+        public void write(FriendlyByteBuf buffer) {
+            buffer.writeVarInt(serverVersion);
+        }
+
+        @Override
+        public void handle(Minecraft mc) {
+            if (ModPackets.PACKETS.version == serverVersion)
+                return;
+            Component error = Component.literal("Steam n' Rails on the client uses a different network format than the server.")
```
Comment (patryk3211) [inline src/main/java/org/patryk3211/powergrid/network/PacketSet.java]: Hmm? Probably change this string to Power Grid

File: src/main/java/org/patryk3211/powergrid/network/packets/BlockWireAttachC2SPacket.java [hunk 4]
```diff
@@ -96,17 +94,22 @@ public void handle(Supplier<NetworkManager.PacketContext> context) {
                     endpoint = wire.getEndpoint2();
                 }
             } else {
-                // Junction.
-                endpoint = new DeferredJunctionWireEndpoint(wire, index, gridPoint);
+                // Possibly a junction.
+                endpoint = wire.getEndpoint1();
```
Comment (patryk3211) [inline src/main/java/org/patryk3211/powergrid/network/packets/BlockWireAttachC2SPacket.java]: Why is this constructor removed? Without it, block wires cannot be connected in the middle of each other. This needs to stay.

**Review by patryk3211 — CHANGES_REQUESTED** [review]
Pretty good, just some final changes and it should be ready for merge.

**Comment by tamimbook** [comment]
@Aperre I think @patryk3211 is requesting changes can you look?

**Comment by patryk3211** [comment]
There are certain places where I would use data components but that is something I can handle myself later on. Also it seems like some code will be able to be moved to common thanks to NeoForge, but that's not a high priority matter.

**Comment by tamimbook** [comment]
@Aperre look at the requested changes please. can't wait to play the addon on 1.21.1

File: src/main/java/org/patryk3211/powergrid/network/PacketSet.java (hunk 3 above)
Comment (Aperre) [reply src/main/java/org/patryk3211/powergrid/network/PacketSet.java]: That is my bad didnt check SolidJ PR fully

File: src/main/java/org/patryk3211/powergrid/kinetics/base/ElectricKineticBlock.java (hunk 2 above)
Comment (Aperre) [reply src/main/java/org/patryk3211/powergrid/kinetics/base/ElectricKineticBlock.java]: very much true. I fixed that in new commit

**Review by patryk3211 — APPROVED** [review]
Looks good
