### ISSUE TITLE
[Bug] Crash when placing "Device Connector" Power Grid v0.6.1 + TFMG Community Edition v1.2.4b

### ISSUE THREAD

**Issue by SAMSON320** [patryk3211/PowerGrid#1129]
### Description

Issue:  
Placing or ticking the Create: Power Grid Device Connector causes an immediate crash when TFMG Community Edition is installed.

Crash Type:  
java.lang.AbstractMethodError  
Triggered during block entity ticking.

Root Cause:  
Power Grid’s compatibility class
org.patryk3211.powergrid.compat.tfmg.TFMGCompatDeviceConnectorBlockEntity  
implements TFMG’s IElectric interface but does not implement the new required method:

`long getPos()`

TFMG 1.2.4b introduced this method in IElectric, but Power Grid 0.6.1 still uses the older interface version.
When TFMG calls IElectric.position() or IElectric.setNetwork(), the missing method causes an AbstractMethodError.

Relevant Crash Log Snippet:

```
java.lang.AbstractMethodError: Receiver class 
org.patryk3211.powergrid.compat.tfmg.TFMGCompatDeviceConnectorBlockEntity 
does not define or inherit an implementation of the resolved method 
'abstract long getPos()' of interface com.drmangotea.tfmg.content.electricity.base.IElectric.
```

Reproduction:  
Occurs with a minimal modpack containing only:

- Create
- Create: Power Grid
- TFMG Community Edition
- Architectury API

Placing the Device Connector or loading a world containing it triggers the crash.

### Version

NeoForge 1.21.1

### Game Log

https://mclo.gs/BYWCsUf

**Comment by amsterdamptomatic** [comment]
Quoting Patryk in the discord:
> I have issues when running TFMG and Power Grid together

Power Grid supports TFMG Community Edition which provides new bug fixes.
https://www.curseforge.com/minecraft/mc-mods/tfmg-community-edition
Try using it instead. PG 0.6.1 should work with TFMG 1.2.3 and 1.2.5 (to be released), **version 1.2.4 WILL CRASH**
